# Generated by Django 4.2.6 on 2023-10-14 13:57

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enroll',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.UUIDField()),
                ('image', models.ImageField(upload_to='mydeepface/uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Recognize',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('image', models.ImageField(upload_to='mydeepface/uploads/')),
            ],
        ),
    ]
