# Generated by Django 4.2.6 on 2023-10-14 14:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mykairos', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='image',
            field=models.ImageField(upload_to='mykairos/uploads/'),
        ),
        migrations.AlterField(
            model_name='recognize',
            name='image',
            field=models.ImageField(upload_to='mykairos/uploads/'),
        ),
    ]
