# Generated by Django 4.2.6 on 2023-10-13 17:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('mydeepface', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enroll',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
    ]
